# -*- coding: utf-8 -*-
"""Hotel_Booking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19pdnyxIt4izBBoYAu4ZGXHIHHkqhanAw
"""

# Importing Libraries

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Loading Dataset

df = pd.read_csv('hotel_bookings 2.csv')

# EDA and Data Cleaning

df.head()

df.tail()

df.head(10)

df.shape

df.columns

df.info()

df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'], dayfirst=True)

df.info()

df.describe(include='object')

df.describe()

for col in df.describe(include='object').columns:
    print(col)
    print(df[col].unique())
    print('-'*50) # DOUBT #

df.isnull().sum()

df.drop(['company','agent'], axis=1, inplace=True, errors='ignore')
df.dropna(inplace=True)

df.isnull().sum()

df.describe()

df['adr'].plot(kind='box')

df=df[df['adr']<5000]

df.describe()

df['adr'].plot(kind='box')

# DATA ANALYSIS AND VISUALIZATIONS

df.head()

Cancelled_perc = df['is_canceled'].value_counts(normalize=True)
print(Cancelled_perc)

plt.figure(figsize=(5,5))
plt.pie(Cancelled_perc, labels=Cancelled_perc.index, autopct='%1.2f%%', startangle=90)
plt.title('Booking Cancellation')
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(x='hotel', hue='is_canceled', data=df)
plt.title('Booking Cancellation')
plt.xlabel('Hotel')
plt.ylabel('Number of Bookings')
plt.show()

resort_hotel = df[df['hotel']=='Resort Hotel']
resort_hotel['is_canceled'].value_counts(normalize=True)

city_hotel = df[df['hotel']=='City Hotel']
city_hotel['is_canceled'].value_counts(normalize=True)

# 'adr'= Average Daily Rate

resort_hotel = resort_hotel.groupby('reservation_status_date')['adr'].mean()
city_hotel = city_hotel.groupby('reservation_status_date')['adr'].mean()

plt.figure(figsize=(20,8))
plt.plot(resort_hotel.index, resort_hotel.values, label='Resort Hotel')
plt.plot(city_hotel.index, city_hotel.values, label='City Hotel')
plt.title('Average Daily Rate (ADR) Over Time')
plt.show()

df['month'] = df['reservation_status_date'].dt.month
plt.figure(figsize=(16,8))
ax1 = sns.countplot(x='month', hue='is_canceled', data=df, palette = 'bright')
legend_labels, _ = ax1.get_legend_handles_labels()
plt.title('Booking Cancellation Over Months')
plt.xlabel('Month')
plt.ylabel('Number of Bookings')
plt.legend(labels=['Not Cancelled', 'Cancelled'])
plt.show()

# higher price then higher cancelation rate

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15,8))
plt.title('ADR per month',fontsize=30)
sns.barplot(x='month',y='adr', data=df[df['is_canceled'] == 1].groupby('month')[['adr']].mean().reset_index())
plt.show()

cancelled_data = df[df['is_canceled'] == 1]
top_10_country = cancelled_data['country'].value_counts()[:10]
plt.figure(figsize=(8,8))
plt.title('Top 10 Countries with Booking Cancellation')
plt.pie(top_10_country, labels=top_10_country.index, autopct='%.2f')
plt.show()

df.head()

# No of reservation

df['market_segment'].value_counts()

# No of cancellation
cancelled_data = df[df['is_canceled'] == 1]
cancelled_data['market_segment'].value_counts()

cancelled_data['market_segment'].value_counts(normalize=True)

